### ISSUE TITLE
[REFACTOR] Alarm Controller, Service, Repository 리팩토링

### ISSUE THREAD

**Issue by dltjdn** [FISOLUTION/BE_ILUVIT#308]
## 📌 Feature Issue

- Alarm Controller, Service, Repository 관련 코드를 아래 TO-DO에 따라 리팩토링 한다

## 📝 To-do

- [x]  불필요한 조인 삭제 
- [x]  기본적인 CRUD : QueryDsl -> Spring Data JPA
- [x]   ResponseEntity로 변경 
- [x]  관련 API Response DTO 만들기
- [x]  노션 API 명세서 업데이트
- [x]  API 테스트 완료
