### ISSUE TITLE
[REFACTOR] Waiting Service, Repository 리팩토링

### ISSUE THREAD

**Issue by ye0ngeun** [FISOLUTION/BE_ILUVIT#319]
## 📌 Feature Issue

- Waiting Service, Repository 관련 코드를 아래 TO-DO에 따라 리팩토링 한다

## 📝 To-do

- [ ]  불필요한 조인 삭제 
- [ ]  기본적인 CRUD : QeuryDsl -> Spring Data JPA
- [ ]  노션 API 명세서 업데이트
- [ ]  API 테스트 완료
