### ISSUE TITLE
[REFACTOR] Child End-to-end 리팩토링

### ISSUE THREAD

**Issue by dltjdn** [FISOLUTION/BE_ILUVIT#334]
## 📌 Feature Issue

- Child Controller, Service, Repository 관련 코드를 아래 TO-DO에 따라 리팩토링 한다

## 📝 To-do

- [x]  메서드 네이밍 규칙을 따라 repository 메서드 변경
- [x]  ResponseEntity로 변경 
- [x]  DTO 컨벤션에 맞게 이름 및 필드 이름 변경
- [x]  노션 API 명세서 업데이트
- [x]  API 테스트 완료
