### ISSUE TITLE
[HOTFIX] 시설 전체 검색 signed 필드 추가

### ISSUE THREAD

**Issue by dltjdn** [FISOLUTION/BE_ILUVIT#360]
## 📌 Feature Issue

- 시설 전체 검색 api 에서 respones dto에 signed 필드를 추가해준다

## 📝 To-do

- [x]  시설 전체 검색 response dto에 signed 필드 추가
- [x]  sql문으로 기존 시설 디비의 signed 값 모두 false로 업데이트
- [x]  signed default 값 false로 설정
- [x]  API 테스트 완료
